#!/usr/bin/env bash
# install.sh :: Installs the Scrabble app and puts a `scrabble` command on $PATH.


set -euo pipefail

APP_BIN_NAME="Scrabble"          # the actual binary shipped in this folder
CMD_NAME="scrabble"              # the command users will type
RESOURCES_DIR="resources"

SYSTEM_INSTALL_DIR="/opt/scrabble"
SYSTEM_BIN_DIR="/usr/local/bin"

USER_INSTALL_DIR="${HOME}/.local/share/scrabble"
USER_BIN_DIR="${HOME}/.local/bin"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"


# Helpers
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'; NC=$'\033[0m'

info()  { printf "%s[INFO]%s  %s\n"  "$BLUE"   "$NC" "$1"; }
ok()    { printf "%s[OK]%s    %s\n"  "$GREEN"  "$NC" "$1"; }
warn()  { printf "%s[WARN]%s  %s\n"  "$YELLOW" "$NC" "$1"; }
err()   { printf "%s[ERROR]%s %s\n"  "$RED"    "$NC" "$1" >&2; }
die()   { err "$1"; exit 1; }

confirm() {
    # confirm "question" -> returns 0 for yes
    local prompt="$1" reply
    read -r -p "$prompt [y/N] " reply </dev/tty
    [[ "$reply" =~ ^[Yy]$ ]]
}


# Checks
info "Checking source files in ${SCRIPT_DIR}..."

[[ -f "${SCRIPT_DIR}/${APP_BIN_NAME}" ]] \
    || die "Could not find '${APP_BIN_NAME}' next to this script. Aborting."

[[ -d "${SCRIPT_DIR}/${RESOURCES_DIR}" ]] \
    || die "Could not find '${RESOURCES_DIR}/' folder next to this script. Aborting."

ok "Found ${APP_BIN_NAME} and ${RESOURCES_DIR}/."


# Choose scope
echo
echo "Where would you like to install Scrabble?"
echo "  1) System-wide  (${SYSTEM_INSTALL_DIR}, command in ${SYSTEM_BIN_DIR}) — requires sudo, all users"
echo "  2) Just for me  (${USER_INSTALL_DIR}, command in ${USER_BIN_DIR}) — no sudo needed"
echo

CHOICE=""
while [[ "$CHOICE" != "1" && "$CHOICE" != "2" ]]; do
    read -r -p "Enter 1 or 2 [2]: " CHOICE </dev/tty
    CHOICE="${CHOICE:-2}"
    if [[ "$CHOICE" != "1" && "$CHOICE" != "2" ]]; then
        warn "Please enter 1 or 2."
    fi
done

if [[ "$CHOICE" == "1" ]]; then
    INSTALL_DIR="$SYSTEM_INSTALL_DIR"
    BIN_DIR="$SYSTEM_BIN_DIR"
    NEED_SUDO=1
else
    INSTALL_DIR="$USER_INSTALL_DIR"
    BIN_DIR="$USER_BIN_DIR"
    NEED_SUDO=0
fi

SUDO=""
if [[ "$NEED_SUDO" -eq 1 && "$EUID" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 || die "System-wide install needs root, and 'sudo' isn't available. Re-run as root instead."
    SUDO="sudo"
    info "System-wide install selected — you may be prompted for your password."
fi

# Handle existing install
if [[ -d "$INSTALL_DIR" ]]; then
    warn "An existing install was found at ${INSTALL_DIR}."
    if confirm "Overwrite it?"; then
        $SUDO rm -rf "$INSTALL_DIR"
    else
        die "Aborted by user."
    fi
fi

# Copy files
info "Installing to ${INSTALL_DIR}..."
$SUDO mkdir -p "$INSTALL_DIR" || die "Failed to create ${INSTALL_DIR}."

$SUDO cp -- "${SCRIPT_DIR}/${APP_BIN_NAME}" "${INSTALL_DIR}/" \
    || die "Failed to copy ${APP_BIN_NAME}."
$SUDO cp -r -- "${SCRIPT_DIR}/${RESOURCES_DIR}" "${INSTALL_DIR}/" \
    || die "Failed to copy ${RESOURCES_DIR}/."

$SUDO chmod +x "${INSTALL_DIR}/${APP_BIN_NAME}"
ok "Files copied."

# Create wrapper on PATH
info "Creating '${CMD_NAME}' command in ${BIN_DIR}..."
$SUDO mkdir -p "$BIN_DIR" || die "Failed to create ${BIN_DIR}."

WRAPPER_PATH="${BIN_DIR}/${CMD_NAME}"

WRAPPER_CONTENT="#!/usr/bin/env bash
# Auto-generated by install.sh — do not edit by hand.
# Runs ${APP_BIN_NAME} with ${INSTALL_DIR} as its working directory so the
# app's relative ./${RESOURCES_DIR} lookup keeps working regardless of
# where this command is invoked from.
set -e
cd \"${INSTALL_DIR}\" || { echo \"scrabble: install directory missing: ${INSTALL_DIR}\" >&2; exit 1; }
exec \"${INSTALL_DIR}/${APP_BIN_NAME}\" \"\$@\"
"

if [[ -n "$SUDO" ]]; then
    printf '%s' "$WRAPPER_CONTENT" | $SUDO tee "$WRAPPER_PATH" >/dev/null
else
    printf '%s' "$WRAPPER_CONTENT" > "$WRAPPER_PATH"
fi

$SUDO chmod +x "$WRAPPER_PATH" || die "Failed to make wrapper executable."
ok "Command installed at ${WRAPPER_PATH}."

# PATH check
echo
if command -v "$CMD_NAME" >/dev/null 2>&1; then
    ok "'${CMD_NAME}' is on your PATH and ready to use."
elif [[ ":$PATH:" == *":${BIN_DIR}:"* ]]; then
    ok "'${BIN_DIR}' is on your PATH. Open a new shell (or run 'hash -r') to pick it up."
else
    warn "${BIN_DIR} is not on your PATH yet."
    echo "  Add this line to your shell config (~/.bashrc, ~/.zshrc, etc.):"
    echo
    echo "    export PATH=\"${BIN_DIR}:\$PATH\""
    echo
    echo "  Then restart your shell or run: source ~/.bashrc"
fi

echo
ok "Installation complete. Try running: ${CMD_NAME}"
